#=======><IMPORT_BOX><========#
import random
from random import randint
from string import *
try:
     import os, storage, requests, mechanize, bs4, futures
except ImportError:
    os.system('clear')


#=======><COLOR><========#
T="\033[1;31m"            # Red
A="\033[1;32m"         # Green
R="\033[1;33m"        # Yellow
RT="\033[1;37m"         # White

#=======><RANDOM_CHOICE_COLOR><========#
color = [T,A,R,RT]
CENT_PH = random.choice(color)
#owner created (cent)
#=======><MODEL'S><========#
Tecno = """

TECNO P3S
TECNO A571LS
TECNO-A7S
TECNO-C5
TECNO-C7
TECNO-C8
TECNO-C9
TECNO-C9S
TECNO CE7j
TECNO CG6
TECNO CG7
TECNO CH6h
TECNO CF7
TECNO CF7S
TECNO CF7k
TECNO CF8
TECNO CC7
TECNO CC7S
TECNO CC6
TECNO CD6
TECNO CD6S
TECNO CD8j
TECNO CD8
TECNO CE7
TECNO CE7j
TECNO CE8
TECNO CD6j
TECNO CG6j
TECNO CG8
TECNO CG8h
TECNO CG7
TECNO CG7n
TECNO CH6
TECNO CH6n
TECNO Mobile CH6n
TECNO CH7
TECNO CH7n
TECNO CI6
TECNO CI6n
TECNO Mobile CI6n
TECNO CI8
TECNO CI8n
TECNO CI7n
TECNO CK7n
TECNO-C7
TECNO CA6
TECNO IN1
TECNO CA7
TECNO CA8
TECNO CA8S
TECNO ID5a
TECNO ID5b
TECNO CB7
TECNO CB7j
TECNO KB3
TECNO ID5
TECNO ID3k
TECNO ID6
TECNO IN6
TECNO IN2
TECNO IN1 Pro
TECNO CA6S
TECNO CB7
TECNO-C9
TECNO Camon CX
TECNO CX Air
TECNO Camon CXS
TECNO IN5
TECNO IN3
TECNO IA5
TECNO P904
TECNO P701
TECNO P702A
TECNO P702
TECNO P702A
TECNO P703
TECNO DP10A
TECNO F1
TECNO F1
TECNO F2
TECNO F2LTE
TECNO H5S
TECNO-J5
TECNO-J7
TECNO-J8
TECNO-L5
TECNO-L8
TECNO L8 Lite
TECNO-L8Plus
TECNO L9
TECNO L9 Plus
TECNO M3S
TECNO-M6S
TECNO-N2
TECNO-N2S
TECNO N5S
TECNO-N6
TECNO-N6S
TECNO N8
TECNO-N8
TECNO-N8R
TECNO-N8S
TECNO-N9
TECNO-N9S
TECNO R8O
TECNO R8S
TECNO P5S
TECNO P702AS
TECNO AD10
TECNO AC8
TECNO AD8
TECNO AD9
TECNO-PHANTOM5
TECNO F3
TECNO F4
TECNO F4 Pro
TECNO B1
TECNO B1S
TECNO BA2
TECNO B1p
TECNO B1f
TECNO RA8
TECNO KB2h
TECNO BB4
TECNO BC1s
TECNO BC3
TECNO BD4i
TECNO BD3
TECNO BE8
TECNO BE8i
TECNO BF7h
TECNO F3
TECNO LD7
TECNO LD7j
TECNO LG7n
TECNO LE6
TECNO LG6n
TECNO AB7
TECNO AX8
TECNO AX8S
TECNO PhonePad 3
TECNO PP7E-DLA1
TECNO PP7E-SLA1
TECNO LA6
TECNO LA7
TECNO LA7 Pro
TECNO LB7
TECNO LC6
TECNO LC6a
TECNO LC7
TECNO LC7S
TECNO LC8
TECNO R6
TECNO RA6
TECNO RA7
TECNO RA6
TECNO RA6S
TECNO S1
TECNO S1M
TECNO S1 Pro
TECNO S1E Pro
TECNO S1E Pro
TECNO SA1
TECNO S6
TECNO S6S
TECNO S6S
TECNO SA1S Pro
TECNO SA6
TECNO SA6S
TECNO KE5
TECNO K7
TECNO KI8
TECNO KA7
TECNO KA7O
TECNO LB6
TECNO KB7
TECNO KB7j
TECNO KB8
TECNO KC8
TECNO KC8S
TECNO BB4k
TECNO KD6
TECNO KD6a
TECNO KE6
TECNO KE6j
TECNO KE5j
TECNO KE5k
TECNO KE5
TECNO KE5k
TECNO KG8
TECNO Mobile KG8
TECNO KG5q
TECNO KA9
TECNO KE5S
TECNO KE5
TECNO BF7n
TECNO BB4k
TECNO K9
TECNO K8
TECNO KA6
TECNO BF7
TECNO BF7n
TECNO AX8
TECNO KC3
TECNO CC9
TECNO CD7
TECNO CE9h
TECNO CE9
TECNO CH9
TECNO CH9n
TECNO CH6IS
TECNO KB2
TECNO KB2j
TECNO CX Air
TECNO K7
TECNO K9
TECNO Mobile KG6k
TECNO Mobile KG5k
TECNO Mobile KG6p
TECNO P904
TECNO AD10
TECNO SC7S
TECNO B1g
TECNO RB8S
TECNO KB2j
TECNO BB2
TECNO BC2
TECNO BC2c
TECNO BC1
TECNO BD2
TECNO BD2d
TECNO BD2p
TECNO BD1
TECNO BD4
TECNO BE7
TECNO BE6
TECNO BE7
TECNO BE6j
TECNO BF6
TECNO L6502S
TECNO LE7
TECNO LE7n
TECNO LF7
TECNO LF7n
TECNO LG7n
TECNO LG8n
TECNO LE8
TECNO R6S
TECNO RC6
TECNO RB7S
TECNO S1 Lite
TECNO SA2S
TECNO SA7S
TECNO KI5n
TECNO KI5q
TECNO KI5k
TECNO KI5m
TECNO KC2
TECNO KC2j
TECNO KC1j
TECNO KC6
TECNO KC6S
TECNO KD7S
TECNO KD7h
TECNO KD7
TECNO KF6
TECNO KF6h
TECNO KF6i
TECNO KF6j
TECNO KF6k
TECNO KF6ks
TECNO KF6m
TECNO KF6n
TECNO KF6p
TECNO PR651
TECNO PR651E
TECNO PR651H
TECNO KF8
TECNO KF7j
TECNO KF6p
TECNO KG6
TECNO KG6k
TECNO KG7
TECNO KG7n
TECNO KG5j
TECNO KG5k
TECNO KG5ks
TECNO KG7n
TECNO KG6P
TECNO KG6p
TECNO KG5p
TECNO KH7S
TECNO KH7n
TECNO KH6
TECNO KC1
TECNO KG5
TECNO KG5h
TECNO KG5m
TECNO P704
TECNO P704a
TECNO-W5
TECNO WX4 Pro S
TECNO-W5
TECNO-Y2
TECNO-Y3+
TECNO W5006S
TECNO-L6
TECNO RB6S
TECNO W1
TECNO W2
TECNO-W3
TECNO W3 Pro
TECNO-W3LTE
TECNO_W4
TECNO-W5
TECNO W5 Lite
TECNO WX3
TECNO WX3F LTE
TECNO WX3F LTE
TECNO WX3LTE
TECNO WX3P
TECNO WX4
TECNO WX4 Pro
TECNO WX4 Pro S
TECNO-Y3
TECNO-Y2
TECNO-Y3+
TECNO-Y3S
TECNO-Y4
TECNO-Y5
TECNO-Y6
TECNO i3
TECNO i3 Pro
TECNO i3 Pro
TECNO i5
TECNO i5 Pro
TECNO i7
TECNO Mobile CH6i
TECNO Mobile AD8
TECNO Mobile LG6n
TECNO Mobile BF7n
TECNO Mobile KI5q

""".splitlines()

galaxy = random.choice(Tecno)

#=======><RANDOM_STRING><========#
fblc = random.choice(["th_TH","en_GB","en_US","fr_FR", "en_US", "es_ES", "de_DE", "it_IT", "ru_RU", "zh_CN", "ja_JP"])
fbpn = random.choice(["com.facebook.katana","com.facebook.lite"])
rt = random.choice(["FB4A","EMA"])
fbcr = random.choice(["AIS','cricket","MegaFon","Viettel Telecom","TRUE-H","TM","GLOBE","null","VIETTEL","TELCEL","O2-CZ","U.S. Cellular","SUN","TelkomSA","Verizon","Plus","Claro BR","T-Mobile","airtel","PLAY (T-Mobile)","VIVACOM","lifecell","Yoigo","life:) BY","vodafone.de","Vodafone","PosteMobile","Verizon Wireless","Movistar","HOME","SAZKAmobilCZ","Astelit-LIFE;FBMF","AT&amp;amp-T","Grameenphone","Robi","Banglalink","Willkommen"])

phone = random.choice(["Tecno"])
fbca = random.choice(["armeabi-v7a:armeabi","arm64-v8a:"])

#=======><UA><========#
CENT = f"{CENT_PH}[FBAN/"+str(rt)+";FBAV/"+str(random.randint(111,458))+".0.0."+str(random.randrange(11,99))+"."+str(random.randint(45,455))+";FBPN/"+str(fbpn)+";FBLC/"+str(fblc)+";FBBV/"+str(random.randint(111111111,999999999))+";FBCR/"+str(fbcr)+";FBMF/"+str(phone)+";FBBD/"+str(phone)+";FBDV/"+str(galaxy)+";FBSV/"+str(random.randint(6,14))+";FBCA/"+str(fbca)+";FBDM/{density=3.0,width=1080,height=1920};FB_FW/1;]"
print(f"UA- {CENT}")
print(f"\033[97;1m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
